name: Cadence change scanner
on:
  pull_request:
    branches:
      - '**'        # match all
    types: [opened, reopened, review_requested]

jobs:
  cdc-check:
    name: Verifying
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
                
      - name: Detect changes to Cadence (.cdc) files
        id: changed-cdc-files
        uses: tj-actions/changed-files@v32
        with:
          files: |
            *.cdc
            **/*.cdc
      
      - name: Formulate pull message 
        if: (steps.changed-cdc-files.outputs.only_changed == 'true' && github.event_name == 'pull_request')
        run: |
          echo "rawJSON={\"type\": \"pull request\", \"repository\": \"${{github.repository}}\",  \"sha\": \"${{github.sha}}\", \"message\": \"${{toJSON(github.event.pull_request.title)}}: ${{toJSON(github.event.pull_request.body)}}\", \"user\": \"${{github.event.pull_request.user.login}}\", \"url\": \"${{github.event.pull_request.html_url}}\", \"changed-date\": \"${{github.event.pull_request.updated_at}}\", \"cdc-changes\": \"${{steps.changed-cdc-files.outputs.all_changed_and_modified_files}}\" }" >> $GITHUB_ENV

      - name: Get Token
        if: (steps.changed-cdc-files.outputs.only_changed == 'true' && env.rawJSON != '')
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Delegate slackbot action
        if: (steps.changed-cdc-files.outputs.only_changed == 'true' && env.rawJSON != '')
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_workflow_token.outputs.token }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'dapperlabs',
              repo: 'sc-eng-internal-ops',
              workflow_id: 'slack-bot.yml',
              ref: 'main',
              inputs: {
                channel: '${{ secrets.CDC_UPDATES_SLACK_CHANNEL }}',
                type: '${{ fromJSON(env.rawJSON).type }}',
                repository: '${{ fromJSON(env.rawJSON).repository }}',
                sha: '${{ fromJSON(env.rawJSON).sha }}',
                message: '${{ fromJSON(env.rawJSON).message }}',
                url: '${{ fromJSON(env.rawJSON).url }}',
                user: '${{ fromJSON(env.rawJSON).user }}',
                'changed-date': '${{ fromJSON(env.rawJSON).changed-date }}',
                'cdc-changes': '${{ fromJSON(env.rawJSON).cdc-changes }}'
              }
            })
